language: python
python:
  - "3.6"
  - "3.6.8"
  - "3.7.4"
  - "3.7.3"
# command to install dependencies
install:
  - make install
# Services for Travis
services: mongodb
#Variables de entorno
env:
  - TRAVIS=yes
# command to run tests
script:
  - make test
