language: python
python:
- '3.6'
- 3.7.3
install:
- make install
services: mongodb
env:
  global:
    - secure: Rfxsyivxmb91TkS1qE+ADSNiHAX+cWdtDdpVONU+QtKiBQJQoTNKASe4lY/Jvt0M7a+q1iCn1o+TkwIOQSKQhEWG+Bbg/RuB2FyKS287cackT6ofq9lSsRzVheA5LEmwyyhp1efvAQ9/Uiqqh5GQGvbNUrvYtSntz61rxB9XQ4x38bh/VckXtu2gDx7ajgDIBe1pVCLSlDE+JMEREnC25xH8wU0NXBNVyzVKEWwN7quKhDBEcpaq2QeZAfrgws7LiZWsEqbBC+KZSvY9QqGNBkT2MoIZx4684fz0b6tV+kKlRKvd0s7ZRlZuKApRe30MaorHZRzsCp3VvO27l/KRyMPBy8pDQGGtEEsy33oroEDjw77KI2LupKBUKmr8XWP4qDCx7Ie8jYZujInIdLhOt9xJurswn+qnIdd0N/ulBdxCAkyRk/bGUpovtVWIap5N86lFVCaG3iB0S6dkUrgHOpHtgbbsUW1Ebm3LWXQyOTXCD2cFgfZQexmxANJi55eGNzhUAtzR2cNniXEu/JcA4IgM/5E3KqkRZ6eMDpZ4HlWGlywY4lQXOU7MedLLbq+gtIPq2e/CtjrFGoJAhfcfg+Z0ar0aQrw8Hao8Ow/ZLBgWJMf/Jf22juGyvEGmNmU7duRwY3op2PcGM5pWogpK/87LbiIcD+thSI92C77LmXA=
script:
- make test
